send_key:
  target:
    entity:
      integration: samsung_tv_frame
      domain: media_player
  fields:
    key:
      required: true
      example: KEY_HOME
      selector:
        text:

set_art_mode:
  target:
    entity:
      integration: samsung_tv_frame
      domain: media_player
  fields:
    enabled:
      required: true
      selector:
        boolean:

select_art:
  target:
    entity:
      integration: samsung_tv_frame
      domain: media_player
  fields:
    content_id:
      required: true
      example: MY_F0034
      selector:
        text:
    show:
      required: false
      default: true
      selector:
        boolean:

upload_art:
  target:
    entity:
      integration: samsung_tv_frame
      domain: media_player
  fields:
    path:
      required: true
      example: /config/www/art/monet.jpg
      selector:
        text:
    matte:
      required: false
      default: none
      example: shadowbox_polar
      selector:
        text:
    show:
      required: false
      default: true
      selector:
        boolean:

delete_art:
  target:
    entity:
      integration: samsung_tv_frame
      domain: media_player
  fields:
    content_id:
      required: true
      example: MY_F0034
      selector:
        text:

set_slideshow:
  target:
    entity:
      integration: samsung_tv_frame
      domain: media_player
  fields:
    duration_minutes:
      required: true
      example: 60
      selector:
        number:
          min: 0
          max: 1440
          unit_of_measurement: min
    shuffle:
      required: false
      default: true
      selector:
        boolean:
    category_id:
      required: false
      default: MY-C0002
      example: MY-C0004
      selector:
        text:

change_matte:
  target:
    entity:
      integration: samsung_tv_frame
      domain: media_player
  fields:
    matte_id:
      required: true
      example: shadowbox_polar
      selector:
        text:
    content_id:
      required: false
      example: MY_F0034
      selector:
        text:

set_photo_filter:
  target:
    entity:
      integration: samsung_tv_frame
      domain: media_player
  fields:
    filter_id:
      required: true
      example: ink
      selector:
        text:
    content_id:
      required: false
      example: MY_F0034
      selector:
        text:

set_favourite:
  target:
    entity:
      integration: samsung_tv_frame
      domain: media_player
  fields:
    favourite:
      required: false
      default: true
      selector:
        boolean:
    content_id:
      required: false
      example: MY_F0034
      selector:
        text:
